version: '3.7'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=Amondin7@yandex.ru"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/letsencrypt:/letsencrypt"
    networks:
      - web

  app:
    build:
      context: .
    image: greenapi-nestjs
    container_name: greenapi-nestjs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.greenapi.rule=Host(`greenapi.gx101.ru`)"
      - "traefik.http.services.greenapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.greenapi.entrypoints=websecure"
      - "traefik.http.routers.greenapi.tls.certresolver=letsencrypt"
    networks:
      - web
    expose:
      - "3000"

networks:
  web:
    external: true